# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_dialog(object):
    def setupUi(self, filter_dialog):
        filter_dialog.setObjectName("filter_dialog")
        filter_dialog.resize(815, 808)
        self.verticalLayout = QtWidgets.QVBoxLayout(filter_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_5 = QtWidgets.QFrame(filter_dialog)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 2, 7, 1, 1)
        self.nproj_label = QtWidgets.QLabel(filter_dialog)
        self.nproj_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nproj_label.setObjectName("nproj_label")
        self.gridLayout.addWidget(self.nproj_label, 1, 3, 1, 1)
        self.ver_downsample_spin = QtWidgets.QSpinBox(filter_dialog)
        self.ver_downsample_spin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ver_downsample_spin.setMinimum(1)
        self.ver_downsample_spin.setMaximum(10)
        self.ver_downsample_spin.setObjectName("ver_downsample_spin")
        self.gridLayout.addWidget(self.ver_downsample_spin, 3, 5, 1, 1)
        self.line = QtWidgets.QFrame(filter_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(filter_dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.line_13 = QtWidgets.QFrame(filter_dialog)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 1, 4, 1, 1)
        self.line_11 = QtWidgets.QFrame(filter_dialog)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 5, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ver_range_0_spin = QtWidgets.QSpinBox(filter_dialog)
        self.ver_range_0_spin.setObjectName("ver_range_0_spin")
        self.horizontalLayout_2.addWidget(self.ver_range_0_spin)
        self.ver_range_1_spin = QtWidgets.QSpinBox(filter_dialog)
        self.ver_range_1_spin.setObjectName("ver_range_1_spin")
        self.horizontalLayout_2.addWidget(self.ver_range_1_spin)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 5, 1, 1)
        self.line_10 = QtWidgets.QFrame(filter_dialog)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 3, 2, 1, 1)
        self.line_15 = QtWidgets.QFrame(filter_dialog)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 5, 4, 1, 1)
        self.line_9 = QtWidgets.QFrame(filter_dialog)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(filter_dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 5, 1, 1)
        self.dataset_combo = QtWidgets.QComboBox(filter_dialog)
        self.dataset_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.dataset_combo.setObjectName("dataset_combo")
        self.gridLayout.addWidget(self.dataset_combo, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.proj_range_0_spin = QtWidgets.QSpinBox(filter_dialog)
        self.proj_range_0_spin.setObjectName("proj_range_0_spin")
        self.horizontalLayout.addWidget(self.proj_range_0_spin)
        self.proj_range_1_spin = QtWidgets.QSpinBox(filter_dialog)
        self.proj_range_1_spin.setObjectName("proj_range_1_spin")
        self.horizontalLayout.addWidget(self.proj_range_1_spin)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 3, 1, 1)
        self.ver_label = QtWidgets.QLabel(filter_dialog)
        self.ver_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ver_label.setObjectName("ver_label")
        self.gridLayout.addWidget(self.ver_label, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(filter_dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(filter_dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(filter_dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.hor_downsample_spin = QtWidgets.QSpinBox(filter_dialog)
        self.hor_downsample_spin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.hor_downsample_spin.setMinimum(1)
        self.hor_downsample_spin.setMaximum(10)
        self.hor_downsample_spin.setObjectName("hor_downsample_spin")
        self.gridLayout.addWidget(self.hor_downsample_spin, 3, 7, 1, 1)
        self.line_8 = QtWidgets.QFrame(filter_dialog)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 4, 7, 1, 1)
        self.line_4 = QtWidgets.QFrame(filter_dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 2, 5, 1, 1)
        self.proj_downsample_spin = QtWidgets.QSpinBox(filter_dialog)
        self.proj_downsample_spin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.proj_downsample_spin.setMinimum(1)
        self.proj_downsample_spin.setMaximum(50)
        self.proj_downsample_spin.setObjectName("proj_downsample_spin")
        self.gridLayout.addWidget(self.proj_downsample_spin, 3, 3, 1, 1)
        self.label = QtWidgets.QLabel(filter_dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(filter_dialog)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 1, 6, 1, 1)
        self.line_7 = QtWidgets.QFrame(filter_dialog)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 4, 5, 1, 1)
        self.line_6 = QtWidgets.QFrame(filter_dialog)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 4, 3, 1, 1)
        self.line_17 = QtWidgets.QFrame(filter_dialog)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout.addWidget(self.line_17, 5, 6, 1, 1)
        self.horizontal_label = QtWidgets.QLabel(filter_dialog)
        self.horizontal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontal_label.setObjectName("horizontal_label")
        self.gridLayout.addWidget(self.horizontal_label, 1, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(filter_dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 7, 1, 1)
        self.line_14 = QtWidgets.QFrame(filter_dialog)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 3, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hor_range_0_spin = QtWidgets.QSpinBox(filter_dialog)
        self.hor_range_0_spin.setObjectName("hor_range_0_spin")
        self.horizontalLayout_3.addWidget(self.hor_range_0_spin)
        self.hor_range_1_spin = QtWidgets.QSpinBox(filter_dialog)
        self.hor_range_1_spin.setObjectName("hor_range_1_spin")
        self.horizontalLayout_3.addWidget(self.hor_range_1_spin)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 7, 1, 1)
        self.line_3 = QtWidgets.QFrame(filter_dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 2, 3, 1, 1)
        self.line_16 = QtWidgets.QFrame(filter_dialog)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 3, 6, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.central_10_btn = QtWidgets.QPushButton(filter_dialog)
        self.central_10_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.central_10_btn.setObjectName("central_10_btn")
        self.horizontalLayout_5.addWidget(self.central_10_btn)
        self.central_50_btn = QtWidgets.QPushButton(filter_dialog)
        self.central_50_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.central_50_btn.setObjectName("central_50_btn")
        self.horizontalLayout_5.addWidget(self.central_50_btn)
        self.central_100_btn = QtWidgets.QPushButton(filter_dialog)
        self.central_100_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.central_100_btn.setObjectName("central_100_btn")
        self.horizontalLayout_5.addWidget(self.central_100_btn)
        self.central_all_btn = QtWidgets.QPushButton(filter_dialog)
        self.central_all_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.central_all_btn.setObjectName("central_all_btn")
        self.horizontalLayout_5.addWidget(self.central_all_btn)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.silx_layout = QtWidgets.QHBoxLayout()
        self.silx_layout.setObjectName("silx_layout")
        self.verticalLayout.addLayout(self.silx_layout)
        self.full_ds_label = QtWidgets.QLabel(filter_dialog)
        self.full_ds_label.setObjectName("full_ds_label")
        self.verticalLayout.addWidget(self.full_ds_label)
        self.red_ds_label = QtWidgets.QLabel(filter_dialog)
        self.red_ds_label.setObjectName("red_ds_label")
        self.verticalLayout.addWidget(self.red_ds_label)
        self.buttonBox = QtWidgets.QDialogButtonBox(filter_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(filter_dialog)
        self.buttonBox.accepted.connect(filter_dialog.accept)
        self.buttonBox.rejected.connect(filter_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(filter_dialog)
        filter_dialog.setTabOrder(self.dataset_combo, self.proj_downsample_spin)
        filter_dialog.setTabOrder(self.proj_downsample_spin, self.ver_downsample_spin)
        filter_dialog.setTabOrder(self.ver_downsample_spin, self.hor_downsample_spin)
        filter_dialog.setTabOrder(self.hor_downsample_spin, self.proj_range_0_spin)
        filter_dialog.setTabOrder(self.proj_range_0_spin, self.proj_range_1_spin)
        filter_dialog.setTabOrder(self.proj_range_1_spin, self.ver_range_0_spin)
        filter_dialog.setTabOrder(self.ver_range_0_spin, self.ver_range_1_spin)
        filter_dialog.setTabOrder(self.ver_range_1_spin, self.hor_range_0_spin)
        filter_dialog.setTabOrder(self.hor_range_0_spin, self.hor_range_1_spin)
        filter_dialog.setTabOrder(self.hor_range_1_spin, self.central_10_btn)
        filter_dialog.setTabOrder(self.central_10_btn, self.central_50_btn)
        filter_dialog.setTabOrder(self.central_50_btn, self.central_100_btn)
        filter_dialog.setTabOrder(self.central_100_btn, self.central_all_btn)

    def retranslateUi(self, filter_dialog):
        _translate = QtCore.QCoreApplication.translate
        filter_dialog.setWindowTitle(_translate("filter_dialog", "pre-load data filter"))
        self.nproj_label.setText(_translate("filter_dialog", "shape[0]"))
        self.label_6.setText(_translate("filter_dialog", "Sub-range: from - to"))
        self.label_2.setText(_translate("filter_dialog", "vertical"))
        self.ver_label.setText(_translate("filter_dialog", "shape[1]"))
        self.label_3.setText(_translate("filter_dialog", "projections"))
        self.label_5.setText(_translate("filter_dialog", "Downsample: load every n-th pixel"))
        self.label.setText(_translate("filter_dialog", "Select dataset with projections:"))
        self.horizontal_label.setText(_translate("filter_dialog", "shape[2]"))
        self.label_4.setText(_translate("filter_dialog", "horizontal"))
        self.central_10_btn.setToolTip(_translate("filter_dialog", "select 10 central slices"))
        self.central_10_btn.setText(_translate("filter_dialog", "10"))
        self.central_50_btn.setToolTip(_translate("filter_dialog", "select 50 central slices"))
        self.central_50_btn.setText(_translate("filter_dialog", "50"))
        self.central_100_btn.setToolTip(_translate("filter_dialog", "select 100 central slices"))
        self.central_100_btn.setText(_translate("filter_dialog", "100"))
        self.central_all_btn.setText(_translate("filter_dialog", "all"))
        self.full_ds_label.setText(_translate("filter_dialog", "Full dataset: 1x1x1 = 1 Gb"))
        self.red_ds_label.setText(_translate("filter_dialog", "Filtered dataset: 1x1x1 = 1 Gb"))
